# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/billing/billing.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'v1/billing/billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v1/billing/billing.proto\x12\nv1.billing\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x19\n\x17\x42illingAddPaymentMethod\"\x1b\n\x19\x42illingListPaymentMethods\"~\n\x15\x42illingProcessPayment\x12\x1a\n\x08\x63urrency\x18\x01 \x01(\tR\x08\x63urrency\x12\x16\n\x06\x61mount\x18\x02 \x01(\x01R\x06\x61mount\x12\"\n\npromo_code\x18\x03 \x01(\tH\x00R\tpromoCode\x88\x01\x01\x42\r\n\x0b_promo_code\"a\n\x0f\x42illingResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12-\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00R\x04\x64\x61ta\x88\x01\x01\x42\x07\n\x05_data2\x92\x02\n\x0e\x42illingService\x12T\n\x10\x41\x64\x64PaymentMethod\x12#.v1.billing.BillingAddPaymentMethod\x1a\x1b.v1.billing.BillingResponse\x12X\n\x12ListPaymentMethods\x12%.v1.billing.BillingListPaymentMethods\x1a\x1b.v1.billing.BillingResponse\x12P\n\x0eProcessPayment\x12!.v1.billing.BillingProcessPayment\x1a\x1b.v1.billing.BillingResponseB*Z(github.com/misterlobo/teachme/v1/billingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.billing.billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/misterlobo/teachme/v1/billing'
  _globals['_BILLINGADDPAYMENTMETHOD']._serialized_start=100
  _globals['_BILLINGADDPAYMENTMETHOD']._serialized_end=125
  _globals['_BILLINGLISTPAYMENTMETHODS']._serialized_start=127
  _globals['_BILLINGLISTPAYMENTMETHODS']._serialized_end=154
  _globals['_BILLINGPROCESSPAYMENT']._serialized_start=156
  _globals['_BILLINGPROCESSPAYMENT']._serialized_end=282
  _globals['_BILLINGRESPONSE']._serialized_start=284
  _globals['_BILLINGRESPONSE']._serialized_end=381
  _globals['_BILLINGSERVICE']._serialized_start=384
  _globals['_BILLINGSERVICE']._serialized_end=658
# @@protoc_insertion_point(module_scope)
