# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.billing import billing_pb2 as v1_dot_billing_dot_billing__pb2


class BillingServiceStub(object):
    """
    Billing Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPaymentMethod = channel.unary_unary(
                '/v1.billing.BillingService/AddPaymentMethod',
                request_serializer=v1_dot_billing_dot_billing__pb2.BillingAddPaymentMethod.SerializeToString,
                response_deserializer=v1_dot_billing_dot_billing__pb2.BillingResponse.FromString,
                _registered_method=True)
        self.ListPaymentMethods = channel.unary_unary(
                '/v1.billing.BillingService/ListPaymentMethods',
                request_serializer=v1_dot_billing_dot_billing__pb2.BillingListPaymentMethods.SerializeToString,
                response_deserializer=v1_dot_billing_dot_billing__pb2.BillingResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/v1.billing.BillingService/ProcessPayment',
                request_serializer=v1_dot_billing_dot_billing__pb2.BillingProcessPayment.SerializeToString,
                response_deserializer=v1_dot_billing_dot_billing__pb2.BillingResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """
    Billing Service
    """

    def AddPaymentMethod(self, request, context):
        """
        AddPaymentMethod
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaymentMethods(self, request, context):
        """
        ListPaymentMethods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """
        ProcessPayment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPaymentMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPaymentMethod,
                    request_deserializer=v1_dot_billing_dot_billing__pb2.BillingAddPaymentMethod.FromString,
                    response_serializer=v1_dot_billing_dot_billing__pb2.BillingResponse.SerializeToString,
            ),
            'ListPaymentMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaymentMethods,
                    request_deserializer=v1_dot_billing_dot_billing__pb2.BillingListPaymentMethods.FromString,
                    response_serializer=v1_dot_billing_dot_billing__pb2.BillingResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=v1_dot_billing_dot_billing__pb2.BillingProcessPayment.FromString,
                    response_serializer=v1_dot_billing_dot_billing__pb2.BillingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.billing.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.billing.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """
    Billing Service
    """

    @staticmethod
    def AddPaymentMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.billing.BillingService/AddPaymentMethod',
            v1_dot_billing_dot_billing__pb2.BillingAddPaymentMethod.SerializeToString,
            v1_dot_billing_dot_billing__pb2.BillingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaymentMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.billing.BillingService/ListPaymentMethods',
            v1_dot_billing_dot_billing__pb2.BillingListPaymentMethods.SerializeToString,
            v1_dot_billing_dot_billing__pb2.BillingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.billing.BillingService/ProcessPayment',
            v1_dot_billing_dot_billing__pb2.BillingProcessPayment.SerializeToString,
            v1_dot_billing_dot_billing__pb2.BillingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
