# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.tutor import tutor_pb2 as v1_dot_tutor_dot_tutor__pb2


class TutorServiceStub(object):
    """
    TutorService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetById = channel.unary_unary(
                '/v1.tutor.TutorService/GetById',
                request_serializer=v1_dot_tutor_dot_tutor__pb2.TutorGetById.SerializeToString,
                response_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/v1.tutor.TutorService/List',
                request_serializer=v1_dot_tutor_dot_tutor__pb2.TutorList.SerializeToString,
                response_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/v1.tutor.TutorService/Search',
                request_serializer=v1_dot_tutor_dot_tutor__pb2.TutorSearch.SerializeToString,
                response_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
                _registered_method=True)
        self.GetAvailableSlots = channel.unary_unary(
                '/v1.tutor.TutorService/GetAvailableSlots',
                request_serializer=v1_dot_tutor_dot_tutor__pb2.TutorGetAvailableSlots.SerializeToString,
                response_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
                _registered_method=True)
        self.SmartSearch = channel.unary_unary(
                '/v1.tutor.TutorService/SmartSearch',
                request_serializer=v1_dot_tutor_dot_tutor__pb2.TutorSmartSearch.SerializeToString,
                response_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/v1.tutor.TutorService/GetPublicKey',
                request_serializer=v1_dot_tutor_dot_tutor__pb2.TutorGetPublicKeyRequest.SerializeToString,
                response_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorGetPublicKeyResponse.FromString,
                _registered_method=True)


class TutorServiceServicer(object):
    """
    TutorService
    """

    def GetById(self, request, context):
        """
        Get tutor by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """
        List
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """
        Search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableSlots(self, request, context):
        """
        GetAvailableSlots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmartSearch(self, request, context):
        """
        SmartSearch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """
        GetPublicKey
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorGetById.FromString,
                    response_serializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorList.FromString,
                    response_serializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorSearch.FromString,
                    response_serializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.SerializeToString,
            ),
            'GetAvailableSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSlots,
                    request_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorGetAvailableSlots.FromString,
                    response_serializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.SerializeToString,
            ),
            'SmartSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SmartSearch,
                    request_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorSmartSearch.FromString,
                    response_serializer=v1_dot_tutor_dot_tutor__pb2.TutorResponse.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=v1_dot_tutor_dot_tutor__pb2.TutorGetPublicKeyRequest.FromString,
                    response_serializer=v1_dot_tutor_dot_tutor__pb2.TutorGetPublicKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.tutor.TutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.tutor.TutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TutorService(object):
    """
    TutorService
    """

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tutor.TutorService/GetById',
            v1_dot_tutor_dot_tutor__pb2.TutorGetById.SerializeToString,
            v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tutor.TutorService/List',
            v1_dot_tutor_dot_tutor__pb2.TutorList.SerializeToString,
            v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tutor.TutorService/Search',
            v1_dot_tutor_dot_tutor__pb2.TutorSearch.SerializeToString,
            v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tutor.TutorService/GetAvailableSlots',
            v1_dot_tutor_dot_tutor__pb2.TutorGetAvailableSlots.SerializeToString,
            v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmartSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tutor.TutorService/SmartSearch',
            v1_dot_tutor_dot_tutor__pb2.TutorSmartSearch.SerializeToString,
            v1_dot_tutor_dot_tutor__pb2.TutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tutor.TutorService/GetPublicKey',
            v1_dot_tutor_dot_tutor__pb2.TutorGetPublicKeyRequest.SerializeToString,
            v1_dot_tutor_dot_tutor__pb2.TutorGetPublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
