// @generated
// This file is @generated by prost-build.
///
/// AppointmentRetrieve
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppointmentRetrieve {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppointmentRetrieveResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attendee_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub date_time: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub duration: i32,
    #[prost(string, tag = "6")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "7")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// AppointmentList
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppointmentList {
    #[prost(string, optional, tag = "1")]
    pub start_date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub end_date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub duration: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppointmentListResponse {
    #[prost(message, repeated, tag = "1")]
    pub past: ::prost::alloc::vec::Vec<AppointmentListEntry>,
    #[prost(message, repeated, tag = "2")]
    pub upcoming: ::prost::alloc::vec::Vec<AppointmentListEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppointmentListEntry {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attendee_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub date_time: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub title: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub access_code: ::prost::alloc::vec::Vec<u8>,
}
///
/// AppointmentResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppointmentResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "5")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "appointment_response::Data", tags = "3, 4")]
    pub data: ::core::option::Option<appointment_response::Data>,
}
/// Nested message and enum types in `AppointmentResponse`.
pub mod appointment_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        List(super::AppointmentListResponse),
        #[prost(message, tag = "4")]
        One(super::AppointmentRetrieveResponse),
    }
}
include!("v1.appointment.tonic.rs");
// @@protoc_insertion_point(module)