// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolGetUserProfile {
    #[prost(string, tag = "1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolMatchTutors {
    #[prost(message, optional, tag = "1")]
    pub profile: ::core::option::Option<ToolUserProfile>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolMatchedTutors {
    #[prost(message, repeated, tag = "1")]
    pub result: ::prost::alloc::vec::Vec<ToolGraphSearchResultsResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolUserProfile {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub first_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub last_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "10")]
    pub categories: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "11")]
    pub subjects: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "12")]
    pub characteristics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub availability: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "14")]
    pub interests: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(double, repeated, tag = "15")]
    pub budget: ::prost::alloc::vec::Vec<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolSearchIntent {
    #[prost(string, optional, tag = "1")]
    pub start_time: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub category: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub subject: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub session_duration: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "6")]
    pub session_price: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "7")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(float, optional, tag = "8")]
    pub confidence: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "9")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(float, repeated, tag = "10")]
    pub embeddings: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolVectorSearch {
    #[prost(message, optional, tag = "1")]
    pub intent: ::core::option::Option<ToolSearchIntent>,
    #[prost(float, repeated, tag = "2")]
    pub embeddings: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolVectorSearchResults {
    #[prost(message, repeated, tag = "1")]
    pub points: ::prost::alloc::vec::Vec<tool_vector_search_results::ToolVectorSearchResultsPoints>,
}
/// Nested message and enum types in `ToolVectorSearchResults`.
pub mod tool_vector_search_results {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ToolVectorSearchResultsPayload {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "2")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub country: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub title: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "5")]
        pub bio: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "6")]
        pub categories: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "7")]
        pub subjects: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "8")]
        pub currency: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(int32, optional, tag = "9")]
        pub session_duration: ::core::option::Option<i32>,
        #[prost(float, optional, tag = "10")]
        pub session_price: ::core::option::Option<f32>,
        #[prost(string, optional, tag = "11")]
        pub locale: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ToolVectorSearchResultsPoints {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub payload: ::core::option::Option<ToolVectorSearchResultsPayload>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolGraphSearch {
    #[prost(string, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolGraphSearchResultsResult {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub bio: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub categories: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub subjects: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "9")]
    pub session_duration: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "10")]
    pub session_price: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "11")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolGraphSearchResults {
    #[prost(message, repeated, tag = "1")]
    pub result: ::prost::alloc::vec::Vec<ToolGraphSearchResultsResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolScheduleSearch {
    #[prost(string, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub timezone: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolScheduleSearchResults {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<tool_schedule_search_results::Result>,
}
/// Nested message and enum types in `ToolScheduleSearchResults`.
pub mod tool_schedule_search_results {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TutorProfileData {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub name: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "3")]
        pub first_name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub last_name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "5")]
        pub country: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "6")]
        pub currency: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "7")]
        pub language: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "8")]
        pub dob: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(int32, optional, tag = "9")]
        pub session_duration: ::core::option::Option<i32>,
        #[prost(float, optional, tag = "10")]
        pub session_price: ::core::option::Option<f32>,
        #[prost(string, optional, tag = "11")]
        pub categories: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "12")]
        pub subjects: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "13")]
        pub title: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "14")]
        pub bio: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "15")]
        pub interests: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(float, optional, tag = "16")]
        pub rating: ::core::option::Option<f32>,
        #[prost(string, optional, tag = "17")]
        pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ToolScheduleSearchResultsSlots {
        #[prost(string, tag = "2")]
        pub date_slot: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "3")]
        pub time_slots: ::prost::alloc::vec::Vec<tool_schedule_search_results_slots::ToolScheduleSearchResultsSlotsTimeSlot>,
    }
    /// Nested message and enum types in `ToolScheduleSearchResultsSlots`.
    pub mod tool_schedule_search_results_slots {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct ToolScheduleSearchResultsSlotsTimeSlot {
            #[prost(string, tag = "1")]
            pub start: ::prost::alloc::string::String,
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Result {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub profile: ::core::option::Option<TutorProfileData>,
        #[prost(message, repeated, tag = "3")]
        pub slots: ::prost::alloc::vec::Vec<ToolScheduleSearchResultsSlots>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolQuerySuggestions {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub suggestions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolSearchResultsResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub status_code: i64,
    #[prost(oneof = "tool_search_results_response::Data", tags = "3, 4, 5, 6, 7")]
    pub data: ::core::option::Option<tool_search_results_response::Data>,
}
/// Nested message and enum types in `ToolSearchResultsResponse`.
pub mod tool_search_results_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        VectorResults(super::ToolVectorSearchResults),
        #[prost(message, tag = "4")]
        GraphResults(super::ToolGraphSearchResults),
        #[prost(message, tag = "5")]
        ScheduleResults(super::ToolScheduleSearchResults),
        #[prost(message, tag = "6")]
        UserProfile(super::ToolUserProfile),
        #[prost(message, tag = "7")]
        MatchedTutors(super::ToolMatchedTutors),
    }
}
include!("v1.tool.tonic.rs");
// @@protoc_insertion_point(module)