// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/payment/payment.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.payment";

/** PaymentSetup */
export interface PaymentSetup {
  recipientId: string;
  senderId?: string | undefined;
}

/** PaymentSetupResponse */
export interface PaymentSetupResponse {
  setupIntentId: string;
  clientSecret?: string | undefined;
}

/** PaymentProcess */
export interface PaymentProcess {
  paymentIntentId: string;
}

/** PaymentProcessResponse */
export interface PaymentProcessResponse {
  paymentIntentId: string;
}

export interface PaymentMethodCard {
  last4: string;
  expMonth: number;
  expYear: number;
  brand?: string | undefined;
  displayBrand?: string | undefined;
  description?: string | undefined;
  country?: string | undefined;
  issuer?: string | undefined;
  fingerprint?: string | undefined;
}

export interface PaymentMethod {
  id: string;
  card?: PaymentMethodCard | undefined;
  type?: string | undefined;
  isDefault?: boolean | undefined;
}

export interface PaymentListMethods {
  default?: boolean | undefined;
}

export interface PaymentListMethodsResponse {
  status: string;
  data: PaymentMethod[];
}

export interface PaymentAttachMethod {
  id: string;
}

export interface PaymentAttachMethodResponse {
  status: string;
  statusCode?: number | undefined;
  error?: string | undefined;
  attachedId?: string | undefined;
}

export const V1_PAYMENT_PACKAGE_NAME = "v1.payment";

/** PaymentService */

export interface PaymentServiceClient {
  /** Setup */

  setup(request: PaymentSetup, metadata: Metadata, ...rest: any): Observable<PaymentSetupResponse>;

  /** Process */

  process(request: PaymentProcess, metadata: Metadata, ...rest: any): Observable<PaymentProcessResponse>;

  /** ListMethods */

  listMethods(request: PaymentListMethods, metadata: Metadata, ...rest: any): Observable<PaymentListMethodsResponse>;

  /** AttachMethod */

  attachMethod(request: PaymentAttachMethod, metadata: Metadata, ...rest: any): Observable<PaymentAttachMethodResponse>;
}

/** PaymentService */

export interface PaymentServiceController {
  /** Setup */

  setup(
    request: PaymentSetup,
    metadata: Metadata,
    ...rest: any
  ): Promise<PaymentSetupResponse> | Observable<PaymentSetupResponse> | PaymentSetupResponse;

  /** Process */

  process(
    request: PaymentProcess,
    metadata: Metadata,
    ...rest: any
  ): Promise<PaymentProcessResponse> | Observable<PaymentProcessResponse> | PaymentProcessResponse;

  /** ListMethods */

  listMethods(
    request: PaymentListMethods,
    metadata: Metadata,
    ...rest: any
  ): Promise<PaymentListMethodsResponse> | Observable<PaymentListMethodsResponse> | PaymentListMethodsResponse;

  /** AttachMethod */

  attachMethod(
    request: PaymentAttachMethod,
    metadata: Metadata,
    ...rest: any
  ): Promise<PaymentAttachMethodResponse> | Observable<PaymentAttachMethodResponse> | PaymentAttachMethodResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["setup", "process", "listMethods", "attachMethod"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
