//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AppointmentStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "appointments")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub host_id: Uuid,
    pub attendee_id: Uuid,
    pub start_at: DateTimeWithTimeZone,
    pub end_at: DateTimeWithTimeZone,
    pub duration: i32,
    pub cal_booking_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub cal_metadata: Option<Json>,
    pub status: Option<AppointmentStatus>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cancel_reason: Option<String>,
    pub cancelled_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::AttendeeId",
        to = "super::students::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::tutors::Entity",
        from = "Column::HostId",
        to = "super::tutors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tutors,
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::tutors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tutors.def()
    }
}
