//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod appointments;
pub mod customers;
pub mod organizations;
pub mod parents;
pub mod purchases;
pub mod sea_orm_active_enums;
pub mod search_prompts;
pub mod students;
pub mod tenants;
pub mod transactions;
pub mod tutor_boosts;
pub mod tutor_embeddings;
pub mod tutor_reviews;
pub mod tutorial_sessions;
pub mod tutors;
pub mod users;
pub mod credit_usages;
pub mod credits;
pub mod subscriptions;