//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::appointments::Entity as Appointments;
pub use super::customers::Entity as Customers;
pub use super::organizations::Entity as Organizations;
pub use super::parents::Entity as Parents;
pub use super::purchases::Entity as Purchases;
pub use super::search_prompts::Entity as SearchPrompts;
pub use super::students::Entity as Students;
pub use super::tenants::Entity as Tenants;
pub use super::transactions::Entity as Transactions;
pub use super::tutorial_sessions::Entity as TutorialSessions;
pub use super::tutors::Entity as Tutors;
pub use super::users::Entity as Users;
