//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "customer_type")]
pub enum CustomerType {
    #[sea_orm(string_value = "student_learner")]
    StudentLearner,
    #[sea_orm(string_value = "parent_guardian")]
    ParentGuardian,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "owner_type")]
pub enum OwnerType {
    #[sea_orm(string_value = "student_learner")]
    StudentLearner,
    #[sea_orm(string_value = "parent_guardian")]
    ParentGuardian,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tenant_type")]
pub enum TenantType {
    #[sea_orm(string_value = "individual")]
    Individual,
    #[sea_orm(string_value = "organization")]
    Organization,
}
