//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::models::subscriptions::UnlockedFeatures;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriptions")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Option<Uuid>,
    pub plan: Option<String>,
    pub stripe_product_id: Option<String>,
    pub stripe_price_id: Option<String>,
    pub stripe_customer_id: Option<String>,
    pub stripe_subscription_id: Option<String>,
    pub period_start: Option<DateTimeWithTimeZone>,
    pub period_end: Option<DateTimeWithTimeZone>,
    pub next_billing_at: Option<DateTimeWithTimeZone>,
    pub trial_active: Option<bool>,
    pub trial_starts_at: Option<DateTimeWithTimeZone>,
    pub trial_ends_at: Option<DateTimeWithTimeZone>,
    pub trial_duration: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub unlocked_features: Option<UnlockedFeatures>,
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
