//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::{FromJsonQueryResult, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, FromJsonQueryResult)]
pub struct Language {
    pub name: String,
    pub proficiency_level: String,
    pub is_primary: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, FromJsonQueryResult)]
pub struct AvailabilitySchedule {
    pub schedule_id: i32,
    pub slug: String,
    pub timezone: String,
    pub is_default: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, FromJsonQueryResult)]
pub struct EventType {
    pub event_type_id: i32,
    pub duration: String,
    pub slug: String,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tutors")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub first_name: String,
    pub last_name: String,
    pub country: String,
    pub city: Option<String>,
    pub currency: String,
    pub title: String,
    pub organization_id: Option<Uuid>,
    pub dob: Option<Date>,
    #[sea_orm(column_type = "JsonBinary")]
    pub primary_language: Language,
    #[sea_orm(column_type = "JsonBinary")]
    pub other_languages: Option<Vec<Language>>,
    pub bio: Option<String>,
    pub categories: Option<String>,
    pub subjects: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub availability_schedules: Option<Vec<AvailabilitySchedule>>,
    #[sea_orm(column_type = "JsonBinary")]
    pub event_types: Option<Vec<EventType>>,
    pub code: Option<String>,
    pub stripe_connect_id: Option<String>,
    pub status: String,
    pub default_calendar: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub calendars: Option<Json>,
    pub tenant_id: Uuid,
    pub session_duration: i32,
    pub session_price: Option<Decimal>,
    // pub embedding: PgVector,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
