//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tutor_reviews")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tutor_id: Uuid,
    pub reviewer_id: Uuid,
    pub reviewer_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub comments: Option<String>,
    pub rating_stars: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tutors::Entity",
        from = "Column::TutorId",
        to = "super::tutors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tutors,
}

impl Related<super::tutors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tutors.def()
    }
}
