//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tutorial_sessions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[serde(rename = "tutorId")]
    pub tutor_id: Uuid,
    #[serde(rename = "studentId")]
    pub student_id: Uuid,
    pub status: Option<String>,
    pub progress: Option<String>,
    #[serde(rename = "appointmentId")]
    pub appointment_id: Uuid,
    #[serde(rename = "sessionLink")]
    pub session_link: Option<String>,
    #[serde(rename = "sessionLength")]
    pub session_length_secs: Option<i32>,
    #[serde(rename = "tenantId")]
    pub tenant_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::appointments::Entity",
        from = "Column::AppointmentId",
        to = "super::appointments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Appointments,
}

impl Related<super::appointments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointments.def()
    }
}
