//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tutors")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[serde(rename = "firstName")]
    pub first_name: String,
    #[serde(rename = "lastName")]
    pub last_name: String,
    pub country: String,
    pub city: Option<String>,
    pub timezone: Option<String>,
    pub currency: String,
    pub title: Option<String>,
    #[serde(rename = "organizationId")]
    pub organization_id: Option<Uuid>,
    pub dob: Option<Date>,
    #[serde(rename = "primaryLanguage")]
    pub primary_language: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(rename = "otherLanguages")]
    pub other_languages: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub languages: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub categories: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub subjects: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(rename = "availabilitySchedules")]
    pub availability_schedules: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub event_types: Option<Json>,
    pub code: Option<String>,
    #[serde(rename = "stripeConnectId")]
    pub stripe_connect_id: Option<String>,
    pub status: String,
    #[serde(rename = "defaultCalendar")]
    pub default_calendar: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub calendars: Option<Json>,
    #[serde(rename = "tenantId")]
    pub tenant_id: Uuid,
    #[serde(rename = "sessionDuration")]
    pub session_duration: i32,
    #[serde(rename = "sessionPrice")]
    pub session_price: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(rename = "calMetadata")]
    pub cal_metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::appointments::Entity")]
    Appointments,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::tutor_boosts::Entity")]
    TutorBoosts,
    #[sea_orm(has_many = "super::tutor_reviews::Entity")]
    TutorReviews,
}

impl Related<super::appointments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointments.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::tutor_boosts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TutorBoosts.def()
    }
}

impl Related<super::tutor_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TutorReviews.def()
    }
}
