// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/account/account.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.account";

/** AccountSetup */
export interface AccountSetup {
}

/** AccountSetupResponse */
export interface AccountSetupResponse {
  status: string;
  setupLink?: string | undefined;
  successLink?: string | undefined;
  refreshLink?: string | undefined;
}

/** AccountVerify */
export interface AccountVerify {
}

/** AccountVerifyResponse */
export interface AccountVerifyResponse {
  status: string;
  verifyLink?: string | undefined;
  successLink?: string | undefined;
  refreshLink?: string | undefined;
}

export interface AccountRetrieve {
  expanded?: boolean | undefined;
  account?: boolean | undefined;
  customer?: boolean | undefined;
  subscription?: boolean | undefined;
}

export interface AccountRetrieveResponse {
  accountId?: string | undefined;
  accountData?: AccountRetrieveResponse_AccountRetrieveAccountData | undefined;
  customerId?: string | undefined;
  customerData?: AccountRetrieveResponse_AccountRetrieveCustomerData | undefined;
  subscriptionId?: string | undefined;
  subscriptionData?: AccountRetrieveResponse_AccountRetrieveSubscriptionData | undefined;
}

export interface AccountRetrieveResponse_AccountRetrieveAccountData {
  id?: string | undefined;
  email?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
}

export interface AccountRetrieveResponse_AccountRetrieveCustomerData {
  id?: string | undefined;
  email?: string | undefined;
  name?: string | undefined;
  status?: string | undefined;
}

export interface AccountRetrieveResponse_AccountRetrieveSubscriptionData {
  id?: string | undefined;
  status?: string | undefined;
}

export const V1_ACCOUNT_PACKAGE_NAME = "v1.account";

/** AccountService */

export interface AccountServiceClient {
  /** Setup */

  setup(request: AccountSetup, metadata: Metadata, ...rest: any): Observable<AccountSetupResponse>;

  /** Verify */

  verify(request: AccountVerify, metadata: Metadata, ...rest: any): Observable<AccountVerifyResponse>;

  /** Retrieve */

  retrieve(request: AccountRetrieve, metadata: Metadata, ...rest: any): Observable<AccountRetrieveResponse>;
}

/** AccountService */

export interface AccountServiceController {
  /** Setup */

  setup(
    request: AccountSetup,
    metadata: Metadata,
    ...rest: any
  ): Promise<AccountSetupResponse> | Observable<AccountSetupResponse> | AccountSetupResponse;

  /** Verify */

  verify(
    request: AccountVerify,
    metadata: Metadata,
    ...rest: any
  ): Promise<AccountVerifyResponse> | Observable<AccountVerifyResponse> | AccountVerifyResponse;

  /** Retrieve */

  retrieve(
    request: AccountRetrieve,
    metadata: Metadata,
    ...rest: any
  ): Promise<AccountRetrieveResponse> | Observable<AccountRetrieveResponse> | AccountRetrieveResponse;
}

export function AccountServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["setup", "verify", "retrieve"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ACCOUNT_SERVICE_NAME = "AccountService";
