[workspace]
resolver = "3"
members = ["apps/signal", "apps/wasm-worker"]


[workspace.dependencies]
loco-rs = { version = "0.16", features = ["bg_redis", "cache_redis"] }
prost = "0.14.3"
tonic = { version = "0.14.5", features = ["transport", "server", "channel", "gzip", "tls-ring"] }
tonic-prost = "0.14.5"
prost-types = "0.14.3"
rand = { version = "0.10" }
rand_core = "0.10"
opaque-ke = { version = "4.0.1", features = ["argon2"] }
base64 = "0.22.1"

#[patch.crates-io]
#sea-orm = { version = "2.0.0-rc" }