// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/appointment/appointment.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.appointment";

/** AppointmentRetrieve */
export interface AppointmentRetrieve {
  id: string;
}

export interface AppointmentRetrieveResponse {
  id: string;
  hostId: string;
  attendeeId: string;
  dateTime: string;
  duration: number;
  title: string;
  description?: string | undefined;
}

/** AppointmentList */
export interface AppointmentList {
  startDate?: string | undefined;
  endDate?: string | undefined;
  duration?: number | undefined;
}

export interface AppointmentListResponse {
  past: AppointmentListEntry[];
  upcoming: AppointmentListEntry[];
}

export interface AppointmentListEntry {
  id: string;
  hostId: string;
  attendeeId: string;
  dateTime: string;
  status: string;
  title: string;
  accessCode: Uint8Array;
}

/** AppointmentResponse */
export interface AppointmentResponse {
  status: string;
  statusCode: number;
  list?: AppointmentListResponse | undefined;
  one?: AppointmentRetrieveResponse | undefined;
  error?: string | undefined;
}

export const V1_APPOINTMENT_PACKAGE_NAME = "v1.appointment";

/** Booking Service */

export interface AppointmentServiceClient {
  /** Retrieve an appointment */

  retrieve(request: AppointmentRetrieve, metadata: Metadata, ...rest: any): Observable<AppointmentResponse>;

  /** List appointments */

  list(request: AppointmentList, metadata: Metadata, ...rest: any): Observable<AppointmentResponse>;
}

/** Booking Service */

export interface AppointmentServiceController {
  /** Retrieve an appointment */

  retrieve(
    request: AppointmentRetrieve,
    metadata: Metadata,
    ...rest: any
  ): Promise<AppointmentResponse> | Observable<AppointmentResponse> | AppointmentResponse;

  /** List appointments */

  list(
    request: AppointmentList,
    metadata: Metadata,
    ...rest: any
  ): Promise<AppointmentResponse> | Observable<AppointmentResponse> | AppointmentResponse;
}

export function AppointmentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["retrieve", "list"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AppointmentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AppointmentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const APPOINTMENT_SERVICE_NAME = "AppointmentService";
