// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookingAppointment {
    #[prost(string, tag = "1")]
    pub date_time: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub duration: i32,
    #[prost(string, tag = "3")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub cal_booking_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub cal_booking_metadata: ::core::option::Option<::prost_types::Any>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookingResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
include!("v1.booking.tonic.rs");
// @@protoc_insertion_point(module)