import '@/styles/globals.css'
import { QueryClient } from '@tanstack/react-query'
import AppLayout from './app.layout'
import { getFeatures, isAuthenticated, isCustomer, isTenant } from '@/lib/actions'
import { Toaster } from '@/components/ui/sonner';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient()

  await Promise.all([
    queryClient.prefetchQuery({
      queryKey: ['authenticated'],
      queryFn: isAuthenticated,
    }),
    queryClient.prefetchQuery({
      queryKey: ['isTenant'],
      queryFn: isTenant,
    }),
    queryClient.prefetchQuery({
      queryKey: ['isCustomer'],
      queryFn: isCustomer,
    }),
    queryClient.prefetchQuery({
      queryKey: ['features'],
      queryFn: getFeatures,
    })
  ])
  return (
    <html lang="en" className="dark">
      <body>
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
