// @generated
// This file is @generated by prost-build.
///
/// AuthLogin
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthLogin {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserKey {
    #[prost(string, tag = "1")]
    pub key_cipher: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub salt: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub master_key: ::core::option::Option<user_key::MasterKey>,
    #[prost(string, tag = "5")]
    pub key_cipher_salt: ::prost::alloc::string::String,
}
/// Nested message and enum types in `UserKey`.
pub mod user_key {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct MasterKey {
        #[prost(string, tag = "1")]
        pub wrapped_cipher: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub iv: ::prost::alloc::string::String,
    }
}
///
/// AuthSignup
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthSignup {
    /// \[(validate.rules).string.email = true\];
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    /// \[(validate.rules).string.min_len = 12\];
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// \[(validate.rules).string.min_len = 8\];
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub role: i32,
    #[prost(string, optional, tag = "5")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub categories: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub subjects: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "11")]
    pub primary_language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub plan: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "14")]
    pub is_trial: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "15")]
    pub first_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "16")]
    pub last_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "17")]
    pub session_duration: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "18")]
    pub session_price: ::core::option::Option<i64>,
    #[prost(message, optional, tag = "19")]
    pub keys: ::core::option::Option<UserKey>,
}
///
/// LoginResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub access_token: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub refresh_token: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub keys: ::core::option::Option<UserKey>,
}
///
/// SignupResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignupResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthVerifyPasswordRequest {
    #[prost(string, tag = "1")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthVerifyPasswordResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
include!("v1.auth.tonic.rs");
// @@protoc_insertion_point(module)