// @generated
// This file is @generated by prost-build.
///
/// ProfileGet
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProfileGet {
    #[prost(bool, optional, tag = "1")]
    pub with_availability: ::core::option::Option<bool>,
}
///
/// ProfileUpdate
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfileUpdate {
    #[prost(string, optional, tag = "5")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub categories: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub subjects: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "11")]
    pub primary_language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub plan: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "14")]
    pub is_trial: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "15")]
    pub first_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "16")]
    pub last_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "17")]
    pub session_duration: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "18")]
    pub session_price: ::core::option::Option<f32>,
}
///
/// ProfileData
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfileData {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub first_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub last_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub dob: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "9")]
    pub session_duration: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "10")]
    pub session_price: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "11")]
    pub categories: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub subjects: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub bio: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "15")]
    pub interests: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "16")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "17")]
    pub phone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "18")]
    pub account_verified: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "19")]
    pub payment_verified: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "20")]
    pub passkey_enabled: ::core::option::Option<bool>,
    #[prost(float, optional, tag = "21")]
    pub average_rating: ::core::option::Option<f32>,
    #[prost(int64, optional, tag = "22")]
    pub students: ::core::option::Option<i64>,
    #[prost(string, repeated, tag = "23")]
    pub availability: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "24")]
    pub specialties: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "25")]
    pub private_sessions_enabled: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "26")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "27")]
    pub banner_url: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// TutorProfile
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorProfile {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub first_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub last_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub country: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub language: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub session_duration: i32,
    #[prost(float, tag = "8")]
    pub session_price: f32,
    #[prost(string, tag = "9")]
    pub categories: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub subjects: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub bio: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub other_languages: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub status: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "15")]
    pub verified: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "16")]
    pub payment_verified: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "17")]
    pub phone_verified: ::core::option::Option<bool>,
    #[prost(float, optional, tag = "18")]
    pub rating: ::core::option::Option<f32>,
}
///
/// StudentProfile
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StudentProfile {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub first_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub last_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub country: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub language: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "7")]
    pub dob: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub status: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// ProfileResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfileResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<ProfileData>,
    #[prost(string, optional, tag = "4")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
include!("v1.profile.tonic.rs");
// @@protoc_insertion_point(module)