# Enable Bolt with TLS
dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.bolt.base_directory=/neo4j-data/certs
dbms.ssl.policy.bolt.private_key=bolt-key.pem
dbms.ssl.policy.bolt.public_certificate=bolt-server.pem
dbms.ssl.policy.bolt.trust_certificates=bolt-ca.pem
dbms.ssl.policy.bolt.client_auth=REQUIRE

# Enable HTTPS with TLS
dbms.ssl.policy.https.enabled=true
dbms.ssl.policy.https.base_directory=/neo4j-data/certs
dbms.ssl.policy.https.private_key=client-key.pem
dbms.ssl.policy.https.public_certificate=client-cert.pem
dbms.ssl.policy.https.trust_certificates=client-ca.pem
dbms.ssl.policy.https.client_auth=NONE

# Assign policies to protocols
server.bolt.enabled=true
server.bolt.listen_address=0.0.0.0:7687
server.bolt.tls_ca_file=/neo4j-data/certs/bolt-ca.pem
server.bolt.tls_level=REQUIRED

server.https.enabled=true
server.https.listen_address=:7473
server.memory.pagecache.size=512M

server.default_listen_address=0.0.0.0
server.directories.plugins=/plugins
server.directories.logs=/logs
