# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.auth import auth_pb2 as v1_dot_auth_dot_auth__pb2


class AuthServiceStub(object):
    """
    Auth Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/v1.auth.AuthService/Login',
                request_serializer=v1_dot_auth_dot_auth__pb2.AuthLogin.SerializeToString,
                response_deserializer=v1_dot_auth_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Signup = channel.unary_unary(
                '/v1.auth.AuthService/Signup',
                request_serializer=v1_dot_auth_dot_auth__pb2.AuthSignup.SerializeToString,
                response_deserializer=v1_dot_auth_dot_auth__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.VerifyPassword = channel.unary_unary(
                '/v1.auth.AuthService/VerifyPassword',
                request_serializer=v1_dot_auth_dot_auth__pb2.AuthVerifyPasswordRequest.SerializeToString,
                response_deserializer=v1_dot_auth_dot_auth__pb2.AuthVerifyPasswordResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """
    Auth Service
    """

    def Login(self, request, context):
        """
        Login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Signup(self, request, context):
        """
        Signup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """
        VerifyPassword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=v1_dot_auth_dot_auth__pb2.AuthLogin.FromString,
                    response_serializer=v1_dot_auth_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'Signup': grpc.unary_unary_rpc_method_handler(
                    servicer.Signup,
                    request_deserializer=v1_dot_auth_dot_auth__pb2.AuthSignup.FromString,
                    response_serializer=v1_dot_auth_dot_auth__pb2.SignupResponse.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=v1_dot_auth_dot_auth__pb2.AuthVerifyPasswordRequest.FromString,
                    response_serializer=v1_dot_auth_dot_auth__pb2.AuthVerifyPasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """
    Auth Service
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.auth.AuthService/Login',
            v1_dot_auth_dot_auth__pb2.AuthLogin.SerializeToString,
            v1_dot_auth_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Signup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.auth.AuthService/Signup',
            v1_dot_auth_dot_auth__pb2.AuthSignup.SerializeToString,
            v1_dot_auth_dot_auth__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.auth.AuthService/VerifyPassword',
            v1_dot_auth_dot_auth__pb2.AuthVerifyPasswordRequest.SerializeToString,
            v1_dot_auth_dot_auth__pb2.AuthVerifyPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
