// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/reload/reload.proto

/* eslint-disable */

export const protobufPackage = "v1.reload";

export interface ReloadProto {
  done: boolean;
}

export const V1_RELOAD_PACKAGE_NAME = "v1.reload";
