# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.booking import booking_pb2 as v1_dot_booking_dot_booking__pb2


class BookingServiceStub(object):
    """
    Booking Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/v1.booking.BookingService/Create',
                request_serializer=v1_dot_booking_dot_booking__pb2.BookingCreate.SerializeToString,
                response_deserializer=v1_dot_booking_dot_booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/v1.booking.BookingService/List',
                request_serializer=v1_dot_booking_dot_booking__pb2.BookingList.SerializeToString,
                response_deserializer=v1_dot_booking_dot_booking__pb2.BookingResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """
    Booking Service
    """

    def Create(self, request, context):
        """
        Book an appointment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """
        List
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=v1_dot_booking_dot_booking__pb2.BookingCreate.FromString,
                    response_serializer=v1_dot_booking_dot_booking__pb2.BookingResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=v1_dot_booking_dot_booking__pb2.BookingList.FromString,
                    response_serializer=v1_dot_booking_dot_booking__pb2.BookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """
    Booking Service
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.booking.BookingService/Create',
            v1_dot_booking_dot_booking__pb2.BookingCreate.SerializeToString,
            v1_dot_booking_dot_booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.booking.BookingService/List',
            v1_dot_booking_dot_booking__pb2.BookingList.SerializeToString,
            v1_dot_booking_dot_booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
