// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/auth/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.auth";

/** AuthLogin */
export interface AuthLogin {
  email: string;
  password: string;
}

export interface UserKey {
  keyCipher: string;
  publicKey: string;
  salt: string;
  masterKey: UserKey_MasterKey | undefined;
  keyCipherSalt: string;
}

export interface UserKey_MasterKey {
  wrappedCipher: string;
  iv: string;
}

/** AuthSignup */
export interface AuthSignup {
  /** [(validate.rules).string.email = true]; */
  email: string;
  /** [(validate.rules).string.min_len = 12]; */
  password: string;
  /** [(validate.rules).string.min_len = 8]; */
  username: string;
  role: number;
  country?: string | undefined;
  currency?: string | undefined;
  timezone?: string | undefined;
  title?: string | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  primaryLanguage?: string | undefined;
  locale?: string | undefined;
  plan?: string | undefined;
  isTrial?: boolean | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  keys?: UserKey | undefined;
}

/** LoginResponse */
export interface LoginResponse {
  status: string;
  statusCode: number;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  error?: string | undefined;
  keys?: UserKey | undefined;
}

/** SignupResponse */
export interface SignupResponse {
  status: string;
  statusCode: number;
  error?: string | undefined;
  id?: string | undefined;
}

export interface AuthVerifyPasswordRequest {
  password: string;
}

export interface AuthVerifyPasswordResponse {
  status: string;
  statusCode: number;
  error?: string | undefined;
}

export const V1_AUTH_PACKAGE_NAME = "v1.auth";

/** Auth Service */

export interface AuthServiceClient {
  /** Login */

  login(request: AuthLogin, metadata: Metadata, ...rest: any): Observable<LoginResponse>;

  /** Signup */

  signup(request: AuthSignup, metadata: Metadata, ...rest: any): Observable<SignupResponse>;

  /** VerifyPassword */

  verifyPassword(
    request: AuthVerifyPasswordRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<AuthVerifyPasswordResponse>;
}

/** Auth Service */

export interface AuthServiceController {
  /** Login */

  login(
    request: AuthLogin,
    metadata: Metadata,
    ...rest: any
  ): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  /** Signup */

  signup(
    request: AuthSignup,
    metadata: Metadata,
    ...rest: any
  ): Promise<SignupResponse> | Observable<SignupResponse> | SignupResponse;

  /** VerifyPassword */

  verifyPassword(
    request: AuthVerifyPasswordRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<AuthVerifyPasswordResponse> | Observable<AuthVerifyPasswordResponse> | AuthVerifyPasswordResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "signup", "verifyPassword"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
