# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/embedding/embedding.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'v1/embedding/embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cv1/embedding/embedding.proto\x12\x0cv1.embedding\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"/\n\x0f\x45mbeddingCreate\x12\x1c\n\tdocuments\x18\x01 \x01(\tR\tdocuments\"7\n\x17\x45mbeddingCreateResponse\x12\x1c\n\tembedding\x18\x01 \x03(\x02R\tembedding2b\n\x10\x45mbeddingService\x12N\n\x06\x43reate\x12\x1d.v1.embedding.EmbeddingCreate\x1a%.v1.embedding.EmbeddingCreateResponseB,Z*github.com/misterlobo/teachme/v1/embeddingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.embedding.embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/misterlobo/teachme/v1/embedding'
  _globals['_EMBEDDINGCREATE']._serialized_start=106
  _globals['_EMBEDDINGCREATE']._serialized_end=153
  _globals['_EMBEDDINGCREATERESPONSE']._serialized_start=155
  _globals['_EMBEDDINGCREATERESPONSE']._serialized_end=210
  _globals['_EMBEDDINGSERVICE']._serialized_start=212
  _globals['_EMBEDDINGSERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
