# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.embedding import embedding_pb2 as v1_dot_embedding_dot_embedding__pb2


class EmbeddingServiceStub(object):
    """
    EmbeddingService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/v1.embedding.EmbeddingService/Create',
                request_serializer=v1_dot_embedding_dot_embedding__pb2.EmbeddingCreate.SerializeToString,
                response_deserializer=v1_dot_embedding_dot_embedding__pb2.EmbeddingCreateResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """
    EmbeddingService
    """

    def Create(self, request, context):
        """
        Create
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=v1_dot_embedding_dot_embedding__pb2.EmbeddingCreate.FromString,
                    response_serializer=v1_dot_embedding_dot_embedding__pb2.EmbeddingCreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """
    EmbeddingService
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.embedding.EmbeddingService/Create',
            v1_dot_embedding_dot_embedding__pb2.EmbeddingCreate.SerializeToString,
            v1_dot_embedding_dot_embedding__pb2.EmbeddingCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
