// @generated
// This file is @generated by prost-build.
///
/// CreateEmbedding params
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmbeddingCreate {
    #[prost(string, tag = "1")]
    pub documents: ::prost::alloc::string::String,
}
///
/// CreateEmbeddingResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbeddingCreateResponse {
    #[prost(float, repeated, tag = "1")]
    pub embedding: ::prost::alloc::vec::Vec<f32>,
}
include!("v1.embedding.tonic.rs");
// @@protoc_insertion_point(module)