// @generated
// This file is @generated by prost-build.
///
/// BillingAddPaymentMethod
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingAddPaymentMethod {
}
///
/// BillingListPaymentMethods
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingListPaymentMethods {
}
///
/// BillingProcessPayment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BillingProcessPayment {
    #[prost(string, tag = "1")]
    pub currency: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub amount: f64,
    #[prost(string, optional, tag = "3")]
    pub promo_code: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// BillingResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<::prost_types::Any>,
}
include!("v1.billing.tonic.rs");
// @@protoc_insertion_point(module)