// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/billing/billing.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Any } from "../../google/protobuf/any";

export const protobufPackage = "v1.billing";

/** BillingAddPaymentMethod */
export interface BillingAddPaymentMethod {
}

/** BillingListPaymentMethods */
export interface BillingListPaymentMethods {
}

/** BillingProcessPayment */
export interface BillingProcessPayment {
  currency: string;
  amount: number;
  promoCode?: string | undefined;
}

/** BillingResponse */
export interface BillingResponse {
  status: string;
  data?: Any | undefined;
}

export const V1_BILLING_PACKAGE_NAME = "v1.billing";

/** Billing Service */

export interface BillingServiceClient {
  /** AddPaymentMethod */

  addPaymentMethod(request: BillingAddPaymentMethod, metadata: Metadata, ...rest: any): Observable<BillingResponse>;

  /** ListPaymentMethods */

  listPaymentMethods(request: BillingListPaymentMethods, metadata: Metadata, ...rest: any): Observable<BillingResponse>;

  /** ProcessPayment */

  processPayment(request: BillingProcessPayment, metadata: Metadata, ...rest: any): Observable<BillingResponse>;
}

/** Billing Service */

export interface BillingServiceController {
  /** AddPaymentMethod */

  addPaymentMethod(
    request: BillingAddPaymentMethod,
    metadata: Metadata,
    ...rest: any
  ): Promise<BillingResponse> | Observable<BillingResponse> | BillingResponse;

  /** ListPaymentMethods */

  listPaymentMethods(
    request: BillingListPaymentMethods,
    metadata: Metadata,
    ...rest: any
  ): Promise<BillingResponse> | Observable<BillingResponse> | BillingResponse;

  /** ProcessPayment */

  processPayment(
    request: BillingProcessPayment,
    metadata: Metadata,
    ...rest: any
  ): Promise<BillingResponse> | Observable<BillingResponse> | BillingResponse;
}

export function BillingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addPaymentMethod", "listPaymentMethods", "processPayment"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BillingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BillingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BILLING_SERVICE_NAME = "BillingService";
