// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/embedding/embedding.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.embedding";

/** CreateEmbedding params */
export interface EmbeddingCreate {
  documents: string;
}

/** CreateEmbeddingResponse */
export interface EmbeddingCreateResponse {
  embedding: number[];
}

export const V1_EMBEDDING_PACKAGE_NAME = "v1.embedding";

/** EmbeddingService */

export interface EmbeddingServiceClient {
  /** Create */

  create(request: EmbeddingCreate, metadata: Metadata, ...rest: any): Observable<EmbeddingCreateResponse>;
}

/** EmbeddingService */

export interface EmbeddingServiceController {
  /** Create */

  create(
    request: EmbeddingCreate,
    metadata: Metadata,
    ...rest: any
  ): Promise<EmbeddingCreateResponse> | Observable<EmbeddingCreateResponse> | EmbeddingCreateResponse;
}

export function EmbeddingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EmbeddingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EmbeddingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EMBEDDING_SERVICE_NAME = "EmbeddingService";
