# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.payment import payment_pb2 as v1_dot_payment_dot_payment__pb2


class PaymentServiceStub(object):
    """
    PaymentService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Setup = channel.unary_unary(
                '/v1.payment.PaymentService/Setup',
                request_serializer=v1_dot_payment_dot_payment__pb2.PaymentSetup.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.PaymentSetupResponse.FromString,
                _registered_method=True)
        self.Process = channel.unary_unary(
                '/v1.payment.PaymentService/Process',
                request_serializer=v1_dot_payment_dot_payment__pb2.PaymentProcess.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.PaymentProcessResponse.FromString,
                _registered_method=True)
        self.ListMethods = channel.unary_unary(
                '/v1.payment.PaymentService/ListMethods',
                request_serializer=v1_dot_payment_dot_payment__pb2.PaymentListMethods.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.PaymentListMethodsResponse.FromString,
                _registered_method=True)
        self.AttachMethod = channel.unary_unary(
                '/v1.payment.PaymentService/AttachMethod',
                request_serializer=v1_dot_payment_dot_payment__pb2.PaymentAttachMethod.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.PaymentAttachMethodResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """
    PaymentService
    """

    def Setup(self, request, context):
        """
        Setup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request, context):
        """
        Process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMethods(self, request, context):
        """
        ListMethods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachMethod(self, request, context):
        """
        AttachMethod
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Setup': grpc.unary_unary_rpc_method_handler(
                    servicer.Setup,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.PaymentSetup.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.PaymentSetupResponse.SerializeToString,
            ),
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.PaymentProcess.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.PaymentProcessResponse.SerializeToString,
            ),
            'ListMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMethods,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.PaymentListMethods.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.PaymentListMethodsResponse.SerializeToString,
            ),
            'AttachMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachMethod,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.PaymentAttachMethod.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.PaymentAttachMethodResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """
    PaymentService
    """

    @staticmethod
    def Setup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.payment.PaymentService/Setup',
            v1_dot_payment_dot_payment__pb2.PaymentSetup.SerializeToString,
            v1_dot_payment_dot_payment__pb2.PaymentSetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.payment.PaymentService/Process',
            v1_dot_payment_dot_payment__pb2.PaymentProcess.SerializeToString,
            v1_dot_payment_dot_payment__pb2.PaymentProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.payment.PaymentService/ListMethods',
            v1_dot_payment_dot_payment__pb2.PaymentListMethods.SerializeToString,
            v1_dot_payment_dot_payment__pb2.PaymentListMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.payment.PaymentService/AttachMethod',
            v1_dot_payment_dot_payment__pb2.PaymentAttachMethod.SerializeToString,
            v1_dot_payment_dot_payment__pb2.PaymentAttachMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
