// @generated
// This file is @generated by prost-build.
///
/// AccountSetup
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountSetup {
}
///
/// AccountSetupResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountSetupResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub setup_link: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub success_link: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub refresh_link: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// AccountVerify
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountVerify {
}
///
/// AccountVerifyResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountVerifyResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub verify_link: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub success_link: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub refresh_link: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountRetrieve {
    #[prost(bool, optional, tag = "1")]
    pub expanded: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "2")]
    pub account: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub customer: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "4")]
    pub subscription: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountRetrieveResponse {
    #[prost(oneof = "account_retrieve_response::Account", tags = "1, 2")]
    pub account: ::core::option::Option<account_retrieve_response::Account>,
    #[prost(oneof = "account_retrieve_response::Customer", tags = "3, 4")]
    pub customer: ::core::option::Option<account_retrieve_response::Customer>,
    #[prost(oneof = "account_retrieve_response::Subscription", tags = "5, 6")]
    pub subscription: ::core::option::Option<account_retrieve_response::Subscription>,
}
/// Nested message and enum types in `AccountRetrieveResponse`.
pub mod account_retrieve_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct AccountRetrieveAccountData {
        #[prost(string, optional, tag = "1")]
        pub id: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub email: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub r#type: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub status: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct AccountRetrieveCustomerData {
        #[prost(string, optional, tag = "1")]
        pub id: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub email: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub status: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct AccountRetrieveSubscriptionData {
        #[prost(string, optional, tag = "1")]
        pub id: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub status: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Account {
        #[prost(string, tag = "1")]
        AccountId(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        AccountData(AccountRetrieveAccountData),
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Customer {
        #[prost(string, tag = "3")]
        CustomerId(::prost::alloc::string::String),
        #[prost(message, tag = "4")]
        CustomerData(AccountRetrieveCustomerData),
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Subscription {
        #[prost(string, tag = "5")]
        SubscriptionId(::prost::alloc::string::String),
        #[prost(message, tag = "6")]
        SubscriptionData(AccountRetrieveSubscriptionData),
    }
}
include!("v1.account.tonic.rs");
// @@protoc_insertion_point(module)