# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.tool import tool_pb2 as v1_dot_tool_dot_tool__pb2


class ToolServiceStub(object):
    """
    Booking Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserProfile = channel.unary_unary(
                '/v1.tool.ToolService/GetUserProfile',
                request_serializer=v1_dot_tool_dot_tool__pb2.ToolGetUserProfile.SerializeToString,
                response_deserializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
                _registered_method=True)
        self.MatchTutors = channel.unary_unary(
                '/v1.tool.ToolService/MatchTutors',
                request_serializer=v1_dot_tool_dot_tool__pb2.ToolMatchTutors.SerializeToString,
                response_deserializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_unary(
                '/v1.tool.ToolService/VectorSearch',
                request_serializer=v1_dot_tool_dot_tool__pb2.ToolVectorSearch.SerializeToString,
                response_deserializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
                _registered_method=True)
        self.GraphSearch = channel.unary_unary(
                '/v1.tool.ToolService/GraphSearch',
                request_serializer=v1_dot_tool_dot_tool__pb2.ToolGraphSearch.SerializeToString,
                response_deserializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
                _registered_method=True)
        self.ScheduleSearch = channel.unary_unary(
                '/v1.tool.ToolService/ScheduleSearch',
                request_serializer=v1_dot_tool_dot_tool__pb2.ToolScheduleSearch.SerializeToString,
                response_deserializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
                _registered_method=True)
        self.SaveSuggestions = channel.unary_unary(
                '/v1.tool.ToolService/SaveSuggestions',
                request_serializer=v1_dot_tool_dot_tool__pb2.ToolQuerySuggestions.SerializeToString,
                response_deserializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """
    Booking Service
    """

    def GetUserProfile(self, request, context):
        """
        GetUserProfile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchTutors(self, request, context):
        """
        GetUserProfile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """
        VectorSearch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphSearch(self, request, context):
        """
        GraphSearch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleSearch(self, request, context):
        """
        ScheduleSearch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSuggestions(self, request, context):
        """
        SaveSuggestions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=v1_dot_tool_dot_tool__pb2.ToolGetUserProfile.FromString,
                    response_serializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.SerializeToString,
            ),
            'MatchTutors': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchTutors,
                    request_deserializer=v1_dot_tool_dot_tool__pb2.ToolMatchTutors.FromString,
                    response_serializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=v1_dot_tool_dot_tool__pb2.ToolVectorSearch.FromString,
                    response_serializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.SerializeToString,
            ),
            'GraphSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphSearch,
                    request_deserializer=v1_dot_tool_dot_tool__pb2.ToolGraphSearch.FromString,
                    response_serializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.SerializeToString,
            ),
            'ScheduleSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleSearch,
                    request_deserializer=v1_dot_tool_dot_tool__pb2.ToolScheduleSearch.FromString,
                    response_serializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.SerializeToString,
            ),
            'SaveSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSuggestions,
                    request_deserializer=v1_dot_tool_dot_tool__pb2.ToolQuerySuggestions.FromString,
                    response_serializer=v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.tool.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.tool.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """
    Booking Service
    """

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tool.ToolService/GetUserProfile',
            v1_dot_tool_dot_tool__pb2.ToolGetUserProfile.SerializeToString,
            v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchTutors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tool.ToolService/MatchTutors',
            v1_dot_tool_dot_tool__pb2.ToolMatchTutors.SerializeToString,
            v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tool.ToolService/VectorSearch',
            v1_dot_tool_dot_tool__pb2.ToolVectorSearch.SerializeToString,
            v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tool.ToolService/GraphSearch',
            v1_dot_tool_dot_tool__pb2.ToolGraphSearch.SerializeToString,
            v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tool.ToolService/ScheduleSearch',
            v1_dot_tool_dot_tool__pb2.ToolScheduleSearch.SerializeToString,
            v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.tool.ToolService/SaveSuggestions',
            v1_dot_tool_dot_tool__pb2.ToolQuerySuggestions.SerializeToString,
            v1_dot_tool_dot_tool__pb2.ToolSearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
