// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialRegisterBeginRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialRegisterBeginResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub options_json: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CredentialRegisterFinishRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub enc_mk: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub mk_iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub response: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "5")]
    pub master_keys: ::prost::alloc::vec::Vec<credential_register_finish_request::WrappedMasterKey>,
}
/// Nested message and enum types in `CredentialRegisterFinishRequest`.
pub mod credential_register_finish_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct WrappedMasterKey {
        #[prost(bytes = "vec", tag = "1")]
        pub cipher: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes = "vec", tag = "2")]
        pub iv: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes = "vec", tag = "3")]
        pub recovery_tag: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialRegisterFinishResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub credential_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialLoginBeginRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialLoginBeginResponse {
    #[prost(string, tag = "1")]
    pub challenge: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub rp_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub options_json: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub pid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialLoginFinishRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub response: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialLoginFinishResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub enc_mk: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub prf_salt: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub recovery_tags: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueRegisterBeginRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub client_registration_state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub registration_request: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueRegisterBeginResponse {
    #[prost(string, tag = "1")]
    pub registration_response: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_setup: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueRegisterFinishRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub registration_record: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueRegisterFinishResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpaqueBatchRegisterBeginRequest {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<OpaqueRegisterBeginRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpaqueBatchRegisterBeginRespose {
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<OpaqueRegisterBeginResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpaqueBatchRegisterFinishRequest {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<OpaqueRegisterFinishRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpaqueBatchRegisterFinishResponse {
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<OpaqueRegisterFinishResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueLoginBeginRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub client_login_state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub start_login_request: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueLoginBeginResponse {
    #[prost(string, tag = "1")]
    pub login_response: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_login_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueLoginFinishRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub finish_login_request: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub session_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpaqueLoginFinishResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub salt: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialStoreDeviceParams {
    #[prost(string, tag = "1")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialRetrieveDeviceParams {
    #[prost(string, tag = "1")]
    pub device_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialListDevicesParams {
    #[prost(bool, tag = "1")]
    pub active: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialDevice {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub active: bool,
    #[prost(bool, tag = "5")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CredentialDeviceResponse {
    #[prost(message, repeated, tag = "1")]
    pub devices: ::prost::alloc::vec::Vec<CredentialDevice>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialStoreKeysParams {
    #[prost(bytes = "vec", tag = "1")]
    pub encoded_blob: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub user_key: ::core::option::Option<credential_store_keys_params::UserKey>,
    #[prost(message, optional, tag = "3")]
    pub session_key: ::core::option::Option<credential_store_keys_params::SessionKey>,
    #[prost(message, optional, tag = "4")]
    pub device_key: ::core::option::Option<credential_store_keys_params::DeviceKey>,
    #[prost(string, tag = "5")]
    pub key_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag = "7")]
    pub credential_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "8")]
    pub salt: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CredentialStoreKeysParams`.
pub mod credential_store_keys_params {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct UserKey {
        #[prost(string, tag = "1")]
        pub master_key_cipher: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub salt: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "3")]
        pub key_cipher: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub public_key: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct DeviceKey {
        #[prost(string, tag = "1")]
        pub master_key_cipher: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub salt: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "3")]
        pub key_cipher: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub public_key: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SessionKey {
        #[prost(bytes = "vec", tag = "1")]
        pub code_cipher: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes = "vec", tag = "2")]
        pub salt: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CredentialRetrieveKeysParams {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CredentialResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(oneof = "credential_response::Data", tags = "3, 4, 5")]
    pub data: ::core::option::Option<credential_response::Data>,
}
/// Nested message and enum types in `CredentialResponse`.
pub mod credential_response {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct UserKey {
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SessionKey {
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        UserKey(UserKey),
        #[prost(message, tag = "4")]
        SessionKey(SessionKey),
        #[prost(message, tag = "5")]
        List(super::CredentialDeviceResponse),
    }
}
include!("v1.credential.tonic.rs");
// @@protoc_insertion_point(module)