// @generated
// This file is @generated by prost-build.
///
/// BookingAppointment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookingCreate {
    #[prost(string, tag = "1")]
    pub date_time: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub duration: i32,
    #[prost(string, tag = "3")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub confirmation_token: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub payment_method: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "6")]
    pub enc_access_code: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "7")]
    pub host_session_keys: ::prost::alloc::vec::Vec<booking_create::SessionKey>,
    #[prost(message, repeated, tag = "8")]
    pub guest_session_keys: ::prost::alloc::vec::Vec<booking_create::SessionKey>,
    #[prost(bytes = "vec", tag = "9")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `BookingCreate`.
pub mod booking_create {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SessionKey {
        #[prost(string, tag = "1")]
        pub credential_id: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "2")]
        pub key_ciphertext: ::prost::alloc::vec::Vec<u8>,
        #[prost(string, tag = "3")]
        pub key_type: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookingCreateResponse {
    #[prost(string, optional, tag = "1")]
    pub payment_link: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub payment_intent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub client_secret: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub booking_id: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// BookingResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookingResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "booking_response::Data", tags = "4, 5")]
    pub data: ::core::option::Option<booking_response::Data>,
}
/// Nested message and enum types in `BookingResponse`.
pub mod booking_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "4")]
        Created(super::BookingCreateResponse),
        #[prost(message, tag = "5")]
        Listed(super::BookingListResponse),
    }
}
///
/// BookingList
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookingList {
    #[prost(string, optional, tag = "1")]
    pub start_date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub end_date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub duration: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookingListResponse {
    #[prost(message, optional, tag = "1")]
    pub items: ::core::option::Option<::prost_types::Any>,
}
include!("v1.booking.tonic.rs");
// @@protoc_insertion_point(module)