// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/tool/tool.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.tool";

export interface ToolGetUserProfile {
  pid: string;
  id: string;
}

export interface ToolMatchTutors {
  profile: ToolUserProfile | undefined;
}

export interface ToolMatchedTutors {
  result: ToolGraphSearchResultsResult[];
}

export interface ToolUserProfile {
  id: string;
  email?: string | undefined;
  name?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  country?: string | undefined;
  currency?: string | undefined;
  language?: string | undefined;
  locale?: string | undefined;
  categories: string[];
  subjects: string[];
  characteristics: string[];
  availability?: string | undefined;
  interests: string[];
  budget: number[];
}

export interface ToolSearchIntent {
  startTime?: string | undefined;
  timezone?: string | undefined;
  category?: string | undefined;
  subject?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  currency?: string | undefined;
  confidence?: number | undefined;
  locale?: string | undefined;
  embeddings: number[];
}

export interface ToolVectorSearch {
  intent: ToolSearchIntent | undefined;
  embeddings: number[];
}

export interface ToolVectorSearchResults {
  points: ToolVectorSearchResults_ToolVectorSearchResultsPoints[];
}

export interface ToolVectorSearchResults_ToolVectorSearchResultsPayload {
  id: string;
  name?: string | undefined;
  country?: string | undefined;
  title?: string | undefined;
  bio?: string | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  currency?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  locale?: string | undefined;
}

export interface ToolVectorSearchResults_ToolVectorSearchResultsPoints {
  id: string;
  payload: ToolVectorSearchResults_ToolVectorSearchResultsPayload | undefined;
}

export interface ToolGraphSearch {
  ids: string[];
}

export interface ToolGraphSearchResultsResult {
  id: string;
  name?: string | undefined;
  country?: string | undefined;
  title?: string | undefined;
  bio?: string | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  currency?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  locale?: string | undefined;
}

export interface ToolGraphSearchResults {
  result: ToolGraphSearchResultsResult[];
}

export interface ToolScheduleSearch {
  ids: string[];
  startTime: string;
  timezone: string;
}

export interface ToolScheduleSearchResults {
  results: ToolScheduleSearchResults_Result[];
}

export interface ToolScheduleSearchResults_TutorProfileData {
  id: string;
  name: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  country?: string | undefined;
  currency?: string | undefined;
  language?: string | undefined;
  dob?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  title?: string | undefined;
  bio?: string | undefined;
  interests?: string | undefined;
  rating?: number | undefined;
  timezone?: string | undefined;
}

export interface ToolScheduleSearchResults_ToolScheduleSearchResultsSlots {
  dateSlot: string;
  timeSlots: ToolScheduleSearchResults_ToolScheduleSearchResultsSlots_ToolScheduleSearchResultsSlotsTimeSlot[];
}

export interface ToolScheduleSearchResults_ToolScheduleSearchResultsSlots_ToolScheduleSearchResultsSlotsTimeSlot {
  start: string;
}

export interface ToolScheduleSearchResults_Result {
  id: string;
  profile: ToolScheduleSearchResults_TutorProfileData | undefined;
  slots: ToolScheduleSearchResults_ToolScheduleSearchResultsSlots[];
}

export interface ToolQuerySuggestions {
  userId: string;
  pid: string;
  suggestions: string[];
}

export interface ToolSearchResultsResponse {
  status: string;
  statusCode: number;
  vectorResults?: ToolVectorSearchResults | undefined;
  graphResults?: ToolGraphSearchResults | undefined;
  scheduleResults?: ToolScheduleSearchResults | undefined;
  userProfile?: ToolUserProfile | undefined;
  matchedTutors?: ToolMatchedTutors | undefined;
}

export const V1_TOOL_PACKAGE_NAME = "v1.tool";

/** Booking Service */

export interface ToolServiceClient {
  /** GetUserProfile */

  getUserProfile(request: ToolGetUserProfile, metadata: Metadata, ...rest: any): Observable<ToolSearchResultsResponse>;

  /** GetUserProfile */

  matchTutors(request: ToolMatchTutors, metadata: Metadata, ...rest: any): Observable<ToolSearchResultsResponse>;

  /** VectorSearch */

  vectorSearch(request: ToolVectorSearch, metadata: Metadata, ...rest: any): Observable<ToolSearchResultsResponse>;

  /** GraphSearch */

  graphSearch(request: ToolGraphSearch, metadata: Metadata, ...rest: any): Observable<ToolSearchResultsResponse>;

  /** ScheduleSearch */

  scheduleSearch(request: ToolScheduleSearch, metadata: Metadata, ...rest: any): Observable<ToolSearchResultsResponse>;

  /** SaveSuggestions */

  saveSuggestions(
    request: ToolQuerySuggestions,
    metadata: Metadata,
    ...rest: any
  ): Observable<ToolSearchResultsResponse>;
}

/** Booking Service */

export interface ToolServiceController {
  /** GetUserProfile */

  getUserProfile(
    request: ToolGetUserProfile,
    metadata: Metadata,
    ...rest: any
  ): Promise<ToolSearchResultsResponse> | Observable<ToolSearchResultsResponse> | ToolSearchResultsResponse;

  /** GetUserProfile */

  matchTutors(
    request: ToolMatchTutors,
    metadata: Metadata,
    ...rest: any
  ): Promise<ToolSearchResultsResponse> | Observable<ToolSearchResultsResponse> | ToolSearchResultsResponse;

  /** VectorSearch */

  vectorSearch(
    request: ToolVectorSearch,
    metadata: Metadata,
    ...rest: any
  ): Promise<ToolSearchResultsResponse> | Observable<ToolSearchResultsResponse> | ToolSearchResultsResponse;

  /** GraphSearch */

  graphSearch(
    request: ToolGraphSearch,
    metadata: Metadata,
    ...rest: any
  ): Promise<ToolSearchResultsResponse> | Observable<ToolSearchResultsResponse> | ToolSearchResultsResponse;

  /** ScheduleSearch */

  scheduleSearch(
    request: ToolScheduleSearch,
    metadata: Metadata,
    ...rest: any
  ): Promise<ToolSearchResultsResponse> | Observable<ToolSearchResultsResponse> | ToolSearchResultsResponse;

  /** SaveSuggestions */

  saveSuggestions(
    request: ToolQuerySuggestions,
    metadata: Metadata,
    ...rest: any
  ): Promise<ToolSearchResultsResponse> | Observable<ToolSearchResultsResponse> | ToolSearchResultsResponse;
}

export function ToolServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUserProfile",
      "matchTutors",
      "vectorSearch",
      "graphSearch",
      "scheduleSearch",
      "saveSuggestions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ToolService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ToolService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TOOL_SERVICE_NAME = "ToolService";
