# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.profile import profile_pb2 as v1_dot_profile_dot_profile__pb2


class ProfileServiceStub(object):
    """
    ProfileService provides access to managing user's own profile
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/v1.profile.ProfileService/Get',
                request_serializer=v1_dot_profile_dot_profile__pb2.ProfileGet.SerializeToString,
                response_deserializer=v1_dot_profile_dot_profile__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/v1.profile.ProfileService/Update',
                request_serializer=v1_dot_profile_dot_profile__pb2.ProfileUpdate.SerializeToString,
                response_deserializer=v1_dot_profile_dot_profile__pb2.ProfileResponse.FromString,
                _registered_method=True)


class ProfileServiceServicer(object):
    """
    ProfileService provides access to managing user's own profile
    """

    def Get(self, request, context):
        """
        Get
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """
        Update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=v1_dot_profile_dot_profile__pb2.ProfileGet.FromString,
                    response_serializer=v1_dot_profile_dot_profile__pb2.ProfileResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=v1_dot_profile_dot_profile__pb2.ProfileUpdate.FromString,
                    response_serializer=v1_dot_profile_dot_profile__pb2.ProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.profile.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.profile.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """
    ProfileService provides access to managing user's own profile
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.profile.ProfileService/Get',
            v1_dot_profile_dot_profile__pb2.ProfileGet.SerializeToString,
            v1_dot_profile_dot_profile__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.profile.ProfileService/Update',
            v1_dot_profile_dot_profile__pb2.ProfileUpdate.SerializeToString,
            v1_dot_profile_dot_profile__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
