// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/test/test.proto

/* eslint-disable */

export const protobufPackage = "v1.test";

export interface TestProto {
  done: boolean;
}

export const V1_TEST_PACKAGE_NAME = "v1.test";
