port: 4222
http: 8222
websocket {
  port: 10443
  tls {
    cert_file: "/nats/certs/localhost.san.pem"
    key_file: "/nats/certs/san-key.pem"
    ca_file: "/nats/certs/ca.pem"
  }
  #no_tls: true
}

tls {
  #insecure: true
  cert_file: "/nats/certs/localhost.san.pem"
  key_file: "/nats/certs/san-key.pem"
  ca_file: "/nats/certs/ca.pem"

  verify: true
  verify_and_map: true

  handshake_first: true
}

authorization {
  #users = [
  #  { user: "natsuser", password: "natspassword" }
  #]
  token: "super-secret-token"
}
