// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestProto {
    #[prost(bool, tag = "1")]
    pub done: bool,
}
// @@protoc_insertion_point(module)
