# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.appointment import appointment_pb2 as v1_dot_appointment_dot_appointment__pb2


class AppointmentServiceStub(object):
    """
    Booking Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/v1.appointment.AppointmentService/Retrieve',
                request_serializer=v1_dot_appointment_dot_appointment__pb2.AppointmentRetrieve.SerializeToString,
                response_deserializer=v1_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/v1.appointment.AppointmentService/List',
                request_serializer=v1_dot_appointment_dot_appointment__pb2.AppointmentList.SerializeToString,
                response_deserializer=v1_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                _registered_method=True)


class AppointmentServiceServicer(object):
    """
    Booking Service
    """

    def Retrieve(self, request, context):
        """
        Retrieve an appointment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """
        List appointments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=v1_dot_appointment_dot_appointment__pb2.AppointmentRetrieve.FromString,
                    response_serializer=v1_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=v1_dot_appointment_dot_appointment__pb2.AppointmentList.FromString,
                    response_serializer=v1_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.appointment.AppointmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.appointment.AppointmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppointmentService(object):
    """
    Booking Service
    """

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.appointment.AppointmentService/Retrieve',
            v1_dot_appointment_dot_appointment__pb2.AppointmentRetrieve.SerializeToString,
            v1_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.appointment.AppointmentService/List',
            v1_dot_appointment_dot_appointment__pb2.AppointmentList.SerializeToString,
            v1_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
