// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/profile/profile.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.profile";

/** ProfileGet */
export interface ProfileGet {
  withAvailability?: boolean | undefined;
}

/** ProfileUpdate */
export interface ProfileUpdate {
  country?: string | undefined;
  currency?: string | undefined;
  timezone?: string | undefined;
  title?: string | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  primaryLanguage?: string | undefined;
  locale?: string | undefined;
  plan?: string | undefined;
  isTrial?: boolean | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
}

/** ProfileData */
export interface ProfileData {
  id: string;
  name: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  country?: string | undefined;
  currency?: string | undefined;
  language?: string | undefined;
  dob?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  title?: string | undefined;
  bio?: string | undefined;
  interests?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  accountVerified?: boolean | undefined;
  paymentVerified?: boolean | undefined;
  passkeyEnabled?: boolean | undefined;
  averageRating?: number | undefined;
  students?: number | undefined;
  availability: string[];
  specialties: string[];
  privateSessionsEnabled?: boolean | undefined;
  avatarUrl?: string | undefined;
  bannerUrl?: string | undefined;
}

/** TutorProfile */
export interface TutorProfile {
  id: string;
  firstName: string;
  lastName: string;
  country: string;
  currency: string;
  language: string;
  sessionDuration: number;
  sessionPrice: number;
  categories: string;
  subjects: string;
  title: string;
  bio: string;
  otherLanguages: string;
  status: string;
  verified?: boolean | undefined;
  paymentVerified?: boolean | undefined;
  phoneVerified?: boolean | undefined;
  rating?: number | undefined;
}

/** StudentProfile */
export interface StudentProfile {
  id: string;
  firstName: string;
  lastName: string;
  country: string;
  currency: string;
  language: string;
  dob?: string | undefined;
  status?: string | undefined;
}

/** ProfileResponse */
export interface ProfileResponse {
  status: string;
  statusCode: number;
  data: ProfileData | undefined;
  error?: string | undefined;
}

export const V1_PROFILE_PACKAGE_NAME = "v1.profile";

/** ProfileService provides access to managing user's own profile */

export interface ProfileServiceClient {
  /** Get */

  get(request: ProfileGet, metadata: Metadata, ...rest: any): Observable<ProfileResponse>;

  /** Update */

  update(request: ProfileUpdate, metadata: Metadata, ...rest: any): Observable<ProfileResponse>;
}

/** ProfileService provides access to managing user's own profile */

export interface ProfileServiceController {
  /** Get */

  get(
    request: ProfileGet,
    metadata: Metadata,
    ...rest: any
  ): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  /** Update */

  update(
    request: ProfileUpdate,
    metadata: Metadata,
    ...rest: any
  ): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;
}

export function ProfileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["get", "update"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProfileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProfileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROFILE_SERVICE_NAME = "ProfileService";
