# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.account import account_pb2 as v1_dot_account_dot_account__pb2


class AccountServiceStub(object):
    """
    AccountService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Setup = channel.unary_unary(
                '/v1.account.AccountService/Setup',
                request_serializer=v1_dot_account_dot_account__pb2.AccountSetup.SerializeToString,
                response_deserializer=v1_dot_account_dot_account__pb2.AccountSetupResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/v1.account.AccountService/Verify',
                request_serializer=v1_dot_account_dot_account__pb2.AccountVerify.SerializeToString,
                response_deserializer=v1_dot_account_dot_account__pb2.AccountVerifyResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/v1.account.AccountService/Retrieve',
                request_serializer=v1_dot_account_dot_account__pb2.AccountRetrieve.SerializeToString,
                response_deserializer=v1_dot_account_dot_account__pb2.AccountRetrieveResponse.FromString,
                _registered_method=True)


class AccountServiceServicer(object):
    """
    AccountService
    """

    def Setup(self, request, context):
        """
        Setup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """
        Verify
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """
        Retrieve
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Setup': grpc.unary_unary_rpc_method_handler(
                    servicer.Setup,
                    request_deserializer=v1_dot_account_dot_account__pb2.AccountSetup.FromString,
                    response_serializer=v1_dot_account_dot_account__pb2.AccountSetupResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=v1_dot_account_dot_account__pb2.AccountVerify.FromString,
                    response_serializer=v1_dot_account_dot_account__pb2.AccountVerifyResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=v1_dot_account_dot_account__pb2.AccountRetrieve.FromString,
                    response_serializer=v1_dot_account_dot_account__pb2.AccountRetrieveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.account.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.account.AccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """
    AccountService
    """

    @staticmethod
    def Setup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.account.AccountService/Setup',
            v1_dot_account_dot_account__pb2.AccountSetup.SerializeToString,
            v1_dot_account_dot_account__pb2.AccountSetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.account.AccountService/Verify',
            v1_dot_account_dot_account__pb2.AccountVerify.SerializeToString,
            v1_dot_account_dot_account__pb2.AccountVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.account.AccountService/Retrieve',
            v1_dot_account_dot_account__pb2.AccountRetrieve.SerializeToString,
            v1_dot_account_dot_account__pb2.AccountRetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
