// @generated
// This file is @generated by prost-build.
///
/// PaymentSetup
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentSetup {
    #[prost(string, tag = "1")]
    pub recipient_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub sender_id: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// PaymentSetupResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentSetupResponse {
    #[prost(string, tag = "1")]
    pub setup_intent_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub client_secret: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// PaymentProcess
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentProcess {
    #[prost(string, tag = "1")]
    pub payment_intent_id: ::prost::alloc::string::String,
}
///
/// PaymentProcessResponse
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentProcessResponse {
    #[prost(string, tag = "1")]
    pub payment_intent_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentMethodCard {
    #[prost(string, tag = "1")]
    pub last4: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub exp_month: i64,
    #[prost(int64, tag = "3")]
    pub exp_year: i64,
    #[prost(string, optional, tag = "4")]
    pub brand: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub display_brand: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub issuer: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub fingerprint: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentMethod {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub card: ::core::option::Option<PaymentMethodCard>,
    #[prost(string, optional, tag = "3")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub is_default: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentListMethods {
    #[prost(bool, optional, tag = "1")]
    pub default: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentListMethodsResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<PaymentMethod>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentAttachMethod {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentAttachMethodResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, optional, tag = "2")]
    pub status_code: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub attached_id: ::core::option::Option<::prost::alloc::string::String>,
}
include!("v1.payment.tonic.rs");
// @@protoc_insertion_point(module)