// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: v1/tutor/tutor.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "v1.tutor";

/** TutorGetById params */
export interface TutorGetById {
  id: string;
  withAvailability?: boolean | undefined;
  withRatings?: boolean | undefined;
}

/** TutorList params */
export interface TutorList {
  ids: string[];
  status: string[];
}

/** TutorSearch params */
export interface TutorSearch {
  query: string;
  tz: string;
  userId?: string | undefined;
  pid?: string | undefined;
}

export interface TutorSmartSearch {
  category?: string | undefined;
  subject?: string | undefined;
  country?: string | undefined;
  currency?: string | undefined;
  timezone?: string | undefined;
  sessionDuration?: number | undefined;
  budget: number[];
  startTime?: string | undefined;
  locale?: string | undefined;
  topic?: string | undefined;
  code?: string | undefined;
  availabilityWindow?: string | undefined;
  characteristics?: string | undefined;
  skillLevel?: string | undefined;
}

/** TutorSearchResponse */
export interface TutorSearchResponse {
  category: string;
  subject: string;
  confidence: number;
  currency: string;
  timezone: string;
  sessionDuration: number;
  sessionPrice: number;
  startTime: string;
  locale?: string | undefined;
  topic?: string | undefined;
  embedding: number[];
}

/** TutorGetAvailableSlots */
export interface TutorGetAvailableSlots {
  query: string;
  tz: string;
  userId?: string | undefined;
  pid?: string | undefined;
}

/** ProfileData */
export interface TutorProfileData {
  id: string;
  name: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  country?: string | undefined;
  currency?: string | undefined;
  language?: string | undefined;
  dob?: string | undefined;
  sessionDuration?: number | undefined;
  sessionPrice?: number | undefined;
  categories?: string | undefined;
  subjects?: string | undefined;
  title?: string | undefined;
  bio?: string | undefined;
  interests?: string | undefined;
  rating?: number | undefined;
  timezone?: string | undefined;
}

export interface TutorDateTimeSlots {
  id: string;
  slots: TutorGetAvailableSlotsResponseSlots[];
  profile?: TutorProfileData | undefined;
}

export interface TutorTest {
  id: string;
}

export interface TutorAvailableSlotsResponse {
  slots: TutorDateTimeSlots[];
}

/** TutorGetAvailableSlotsResponseTimeSlot */
export interface TutorGetAvailableSlotsResponseSlots {
  dateSlot: string;
  timeSlots: TutorGetAvailableSlotsResponseTimeSlot[];
}

/** TutorGetAvailableSlotsResponseTimeSlot */
export interface TutorGetAvailableSlotsResponseTimeSlot {
  start: string;
}

/** TutorResponse */
export interface TutorResponse {
  status: string;
  inner?: TutorSearchResponse | undefined;
  outer?: TutorAvailableSlotsResponse | undefined;
}

/** TutorGetEmbedding */
export interface TutorGetEmbedding {
  id: string;
}

/** TutorGetEmbeddingResponse */
export interface TutorGetEmbeddingResponse {
  embedding: number[];
}

export interface TutorGetPublicKeyRequest {
  id: string;
}

export interface TutorGetPublicKeyResponse {
  status: string;
  statusCode: number;
  error?: string | undefined;
  publicKeys: TutorGetPublicKeyResponse_TutorPublicKey[];
}

export interface TutorGetPublicKeyResponse_TutorPublicKey {
  type: string;
  key: Uint8Array;
  credentialId?: string | undefined;
}

export const V1_TUTOR_PACKAGE_NAME = "v1.tutor";

/** TutorService */

export interface TutorServiceClient {
  /** Get tutor by ID */

  getById(request: TutorGetById, metadata: Metadata, ...rest: any): Observable<TutorResponse>;

  /** List */

  list(request: TutorList, metadata: Metadata, ...rest: any): Observable<TutorResponse>;

  /** Search */

  search(request: TutorSearch, metadata: Metadata, ...rest: any): Observable<TutorResponse>;

  /** GetAvailableSlots */

  getAvailableSlots(request: TutorGetAvailableSlots, metadata: Metadata, ...rest: any): Observable<TutorResponse>;

  /** SmartSearch */

  smartSearch(request: TutorSmartSearch, metadata: Metadata, ...rest: any): Observable<TutorResponse>;

  /** GetPublicKey */

  getPublicKey(
    request: TutorGetPublicKeyRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<TutorGetPublicKeyResponse>;
}

/** TutorService */

export interface TutorServiceController {
  /** Get tutor by ID */

  getById(
    request: TutorGetById,
    metadata: Metadata,
    ...rest: any
  ): Promise<TutorResponse> | Observable<TutorResponse> | TutorResponse;

  /** List */

  list(
    request: TutorList,
    metadata: Metadata,
    ...rest: any
  ): Promise<TutorResponse> | Observable<TutorResponse> | TutorResponse;

  /** Search */

  search(
    request: TutorSearch,
    metadata: Metadata,
    ...rest: any
  ): Promise<TutorResponse> | Observable<TutorResponse> | TutorResponse;

  /** GetAvailableSlots */

  getAvailableSlots(
    request: TutorGetAvailableSlots,
    metadata: Metadata,
    ...rest: any
  ): Promise<TutorResponse> | Observable<TutorResponse> | TutorResponse;

  /** SmartSearch */

  smartSearch(
    request: TutorSmartSearch,
    metadata: Metadata,
    ...rest: any
  ): Promise<TutorResponse> | Observable<TutorResponse> | TutorResponse;

  /** GetPublicKey */

  getPublicKey(
    request: TutorGetPublicKeyRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<TutorGetPublicKeyResponse> | Observable<TutorGetPublicKeyResponse> | TutorGetPublicKeyResponse;
}

export function TutorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getById", "list", "search", "getAvailableSlots", "smartSearch", "getPublicKey"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TutorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TutorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TUTOR_SERVICE_NAME = "TutorService";
