// @generated
// This file is @generated by prost-build.
///
/// TutorGetById params
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorGetById {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "2")]
    pub with_availability: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub with_ratings: ::core::option::Option<bool>,
}
///
/// TutorList params
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorList {
    #[prost(string, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub status: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
///
/// TutorSearch params
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorSearch {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tz: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub pid: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorSmartSearch {
    #[prost(string, optional, tag = "1")]
    pub category: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub subject: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "6")]
    pub session_duration: ::core::option::Option<u32>,
    #[prost(float, repeated, tag = "7")]
    pub budget: ::prost::alloc::vec::Vec<f32>,
    #[prost(string, optional, tag = "8")]
    pub start_time: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub topic: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "11")]
    pub code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub availability_window: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub characteristics: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub skill_level: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// TutorSearchResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorSearchResponse {
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub subject: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub confidence: f32,
    #[prost(string, tag = "4")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub timezone: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub session_duration: u32,
    #[prost(float, tag = "7")]
    pub session_price: f32,
    #[prost(string, tag = "8")]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "9")]
    pub locale: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub topic: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(float, repeated, tag = "11")]
    pub embedding: ::prost::alloc::vec::Vec<f32>,
}
///
/// TutorGetAvailableSlots
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorGetAvailableSlots {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tz: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub pid: ::core::option::Option<::prost::alloc::string::String>,
}
///
/// ProfileData
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorProfileData {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub first_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub last_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub currency: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub dob: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "9")]
    pub session_duration: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "10")]
    pub session_price: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "11")]
    pub categories: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub subjects: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub bio: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "15")]
    pub interests: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(float, optional, tag = "16")]
    pub rating: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "17")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorDateTimeSlots {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub slots: ::prost::alloc::vec::Vec<TutorGetAvailableSlotsResponseSlots>,
    #[prost(message, optional, tag = "3")]
    pub profile: ::core::option::Option<TutorProfileData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorTest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorAvailableSlotsResponse {
    #[prost(message, repeated, tag = "1")]
    pub slots: ::prost::alloc::vec::Vec<TutorDateTimeSlots>,
}
///
/// TutorGetAvailableSlotsResponseTimeSlot
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorGetAvailableSlotsResponseSlots {
    #[prost(string, tag = "1")]
    pub date_slot: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub time_slots: ::prost::alloc::vec::Vec<TutorGetAvailableSlotsResponseTimeSlot>,
}
///
/// TutorGetAvailableSlotsResponseTimeSlot
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorGetAvailableSlotsResponseTimeSlot {
    #[prost(string, tag = "1")]
    pub start: ::prost::alloc::string::String,
}
///
/// TutorResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(oneof = "tutor_response::Data", tags = "2, 3")]
    pub data: ::core::option::Option<tutor_response::Data>,
}
/// Nested message and enum types in `TutorResponse`.
pub mod tutor_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "2")]
        Inner(super::TutorSearchResponse),
        #[prost(message, tag = "3")]
        Outer(super::TutorAvailableSlotsResponse),
    }
}
///
/// TutorGetEmbedding
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorGetEmbedding {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
///
/// TutorGetEmbeddingResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorGetEmbeddingResponse {
    #[prost(float, repeated, tag = "1")]
    pub embedding: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TutorGetPublicKeyRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TutorGetPublicKeyResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub public_keys: ::prost::alloc::vec::Vec<tutor_get_public_key_response::TutorPublicKey>,
}
/// Nested message and enum types in `TutorGetPublicKeyResponse`.
pub mod tutor_get_public_key_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct TutorPublicKey {
        #[prost(string, tag = "1")]
        pub r#type: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "2")]
        pub key: ::prost::alloc::vec::Vec<u8>,
        #[prost(string, optional, tag = "3")]
        pub credential_id: ::core::option::Option<::prost::alloc::string::String>,
    }
}
include!("v1.tutor.tonic.rs");
// @@protoc_insertion_point(module)