# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.credential import credential_pb2 as v1_dot_credential_dot_credential__pb2


class CredentialServiceStub(object):
    """
    Booking Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreDevice = channel.unary_unary(
                '/v1.credential.CredentialService/StoreDevice',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialStoreDeviceParams.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.RetrieveDevice = channel.unary_unary(
                '/v1.credential.CredentialService/RetrieveDevice',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialRetrieveDeviceParams.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/v1.credential.CredentialService/ListDevices',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialListDevicesParams.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.StoreKeys = channel.unary_unary(
                '/v1.credential.CredentialService/StoreKeys',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialStoreKeysParams.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.SaveKey = channel.unary_unary(
                '/v1.credential.CredentialService/SaveKey',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialStoreKeysParams.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.RetrieveKeys = channel.unary_unary(
                '/v1.credential.CredentialService/RetrieveKeys',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialRetrieveKeysParams.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.RegisterBegin = channel.unary_unary(
                '/v1.credential.CredentialService/RegisterBegin',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialRegisterBeginResponse.FromString,
                _registered_method=True)
        self.RegisterFinish = channel.unary_unary(
                '/v1.credential.CredentialService/RegisterFinish',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialRegisterFinishRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialRegisterFinishResponse.FromString,
                _registered_method=True)
        self.LoginBegin = channel.unary_unary(
                '/v1.credential.CredentialService/LoginBegin',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialLoginBeginRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialLoginBeginResponse.FromString,
                _registered_method=True)
        self.LoginFinish = channel.unary_unary(
                '/v1.credential.CredentialService/LoginFinish',
                request_serializer=v1_dot_credential_dot_credential__pb2.CredentialLoginFinishRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.CredentialLoginFinishResponse.FromString,
                _registered_method=True)
        self.OpaqueRegisterBegin = channel.unary_unary(
                '/v1.credential.CredentialService/OpaqueRegisterBegin',
                request_serializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterBeginRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterBeginResponse.FromString,
                _registered_method=True)
        self.OpaqueRegisterFinish = channel.unary_unary(
                '/v1.credential.CredentialService/OpaqueRegisterFinish',
                request_serializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterFinishRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterFinishResponse.FromString,
                _registered_method=True)
        self.OpaqueLoginBegin = channel.unary_unary(
                '/v1.credential.CredentialService/OpaqueLoginBegin',
                request_serializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginBeginRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginBeginResponse.FromString,
                _registered_method=True)
        self.OpaqueLoginFinish = channel.unary_unary(
                '/v1.credential.CredentialService/OpaqueLoginFinish',
                request_serializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginFinishRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginFinishResponse.FromString,
                _registered_method=True)
        self.OpaqueBatchRegisterBegin = channel.unary_unary(
                '/v1.credential.CredentialService/OpaqueBatchRegisterBegin',
                request_serializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterBeginRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterBeginRespose.FromString,
                _registered_method=True)
        self.OpaqueBatchRegisterFinish = channel.unary_unary(
                '/v1.credential.CredentialService/OpaqueBatchRegisterFinish',
                request_serializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterFinishRequest.SerializeToString,
                response_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterFinishResponse.FromString,
                _registered_method=True)


class CredentialServiceServicer(object):
    """
    Booking Service
    """

    def StoreDevice(self, request, context):
        """
        Store a Credential
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveDevice(self, request, context):
        """
        Retrieve a Credential
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """
        List Credentials
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterBegin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFinish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginBegin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginFinish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpaqueRegisterBegin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpaqueRegisterFinish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpaqueLoginBegin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpaqueLoginFinish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpaqueBatchRegisterBegin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpaqueBatchRegisterFinish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreDevice,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialStoreDeviceParams.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.SerializeToString,
            ),
            'RetrieveDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveDevice,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialRetrieveDeviceParams.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialListDevicesParams.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.SerializeToString,
            ),
            'StoreKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreKeys,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialStoreKeysParams.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.SerializeToString,
            ),
            'SaveKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveKey,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialStoreKeysParams.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.SerializeToString,
            ),
            'RetrieveKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveKeys,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialRetrieveKeysParams.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialResponse.SerializeToString,
            ),
            'RegisterBegin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBegin,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialRegisterBeginResponse.SerializeToString,
            ),
            'RegisterFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFinish,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialRegisterFinishRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialRegisterFinishResponse.SerializeToString,
            ),
            'LoginBegin': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginBegin,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialLoginBeginRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialLoginBeginResponse.SerializeToString,
            ),
            'LoginFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginFinish,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.CredentialLoginFinishRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.CredentialLoginFinishResponse.SerializeToString,
            ),
            'OpaqueRegisterBegin': grpc.unary_unary_rpc_method_handler(
                    servicer.OpaqueRegisterBegin,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterBeginRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterBeginResponse.SerializeToString,
            ),
            'OpaqueRegisterFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.OpaqueRegisterFinish,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterFinishRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.OpaqueRegisterFinishResponse.SerializeToString,
            ),
            'OpaqueLoginBegin': grpc.unary_unary_rpc_method_handler(
                    servicer.OpaqueLoginBegin,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginBeginRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginBeginResponse.SerializeToString,
            ),
            'OpaqueLoginFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.OpaqueLoginFinish,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginFinishRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.OpaqueLoginFinishResponse.SerializeToString,
            ),
            'OpaqueBatchRegisterBegin': grpc.unary_unary_rpc_method_handler(
                    servicer.OpaqueBatchRegisterBegin,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterBeginRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterBeginRespose.SerializeToString,
            ),
            'OpaqueBatchRegisterFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.OpaqueBatchRegisterFinish,
                    request_deserializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterFinishRequest.FromString,
                    response_serializer=v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterFinishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.credential.CredentialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.credential.CredentialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredentialService(object):
    """
    Booking Service
    """

    @staticmethod
    def StoreDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/StoreDevice',
            v1_dot_credential_dot_credential__pb2.CredentialStoreDeviceParams.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/RetrieveDevice',
            v1_dot_credential_dot_credential__pb2.CredentialRetrieveDeviceParams.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/ListDevices',
            v1_dot_credential_dot_credential__pb2.CredentialListDevicesParams.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/StoreKeys',
            v1_dot_credential_dot_credential__pb2.CredentialStoreKeysParams.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/SaveKey',
            v1_dot_credential_dot_credential__pb2.CredentialStoreKeysParams.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/RetrieveKeys',
            v1_dot_credential_dot_credential__pb2.CredentialRetrieveKeysParams.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterBegin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/RegisterBegin',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialRegisterBeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/RegisterFinish',
            v1_dot_credential_dot_credential__pb2.CredentialRegisterFinishRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialRegisterFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginBegin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/LoginBegin',
            v1_dot_credential_dot_credential__pb2.CredentialLoginBeginRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialLoginBeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/LoginFinish',
            v1_dot_credential_dot_credential__pb2.CredentialLoginFinishRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.CredentialLoginFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpaqueRegisterBegin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/OpaqueRegisterBegin',
            v1_dot_credential_dot_credential__pb2.OpaqueRegisterBeginRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.OpaqueRegisterBeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpaqueRegisterFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/OpaqueRegisterFinish',
            v1_dot_credential_dot_credential__pb2.OpaqueRegisterFinishRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.OpaqueRegisterFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpaqueLoginBegin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/OpaqueLoginBegin',
            v1_dot_credential_dot_credential__pb2.OpaqueLoginBeginRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.OpaqueLoginBeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpaqueLoginFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/OpaqueLoginFinish',
            v1_dot_credential_dot_credential__pb2.OpaqueLoginFinishRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.OpaqueLoginFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpaqueBatchRegisterBegin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/OpaqueBatchRegisterBegin',
            v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterBeginRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterBeginRespose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpaqueBatchRegisterFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.credential.CredentialService/OpaqueBatchRegisterFinish',
            v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterFinishRequest.SerializeToString,
            v1_dot_credential_dot_credential__pb2.OpaqueBatchRegisterFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
